name: K6 Performance Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  issues: write

jobs:
  performance-test:
    name: Run K6 Performance Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Create results directory
        run: mkdir -p results
      
      - name: Run k6 tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/load-test.js
          flags: --out json=results/load-test.json --summary-export=results/load-test-summary.json

      - name: Run stress test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/stress-test.js
          flags: --out json=results/stress-test.json --summary-export=results/stress-test-summary.json

      - name: Run spike test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/spike-test.js
          flags: --out json=results/spike-test.json --summary-export=results/spike-test-summary.json
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-test-results
          path: |
            results/*.json